SonarSource/sonar-analyzer-commons

test-commons/src/main/java/com/sonarsource/checks/verifier/TestFile.java
test-commons/src/test/java/com/sonarsource/checks/verifier/FileIssuesTest.java
test-commons/src/test/resources/code.js
test-commons/src/test/resources/code.js.issues.txt

Make tabulation visible in the report

---

test-commons/src/main/java/com/sonarsource/checks/verifier/internal/LineIssues.java
test-commons/src/test/java/com/sonarsource/checks/verifier/SingleFileVerifierTest.java

Support several messages on the same line regardless of the occurrence order.

---

commons/src/main/java/org/sonarsource/analyzer/commons/ProfileGenerator.java
commons/src/test/java/org/sonarsource/analyzer/commons/ProfileGeneratorTest.java
test-commons/src/test/java/com/sonarsource/checks/verifier/FileContentTest.java
travis.sh

Ruling profile generator

---

test-commons/src/main/java/com/sonarsource/checks/verifier/internal/FileIssues.java
test-commons/src/main/java/com/sonarsource/checks/verifier/internal/InternalIssueVerifier.java
test-commons/src/main/java/com/sonarsource/checks/verifier/internal/PerLineLocationWriter.java
test-commons/src/main/java/com/sonarsource/checks/verifier/internal/Report.java
test-commons/src/main/java/com/sonarsource/checks/verifier/internal/ReportDiff.java
test-commons/src/test/java/com/sonarsource/checks/verifier/MultiFileVerifierTest.java
test-commons/src/test/java/com/sonarsource/checks/verifier/PerLineLocationWriterTest.java
test-commons/src/test/java/com/sonarsource/checks/verifier/SingleFileVerifierTest.java
test-commons/src/test/java/com/sonarsource/checks/verifier/internal/ReportDiffTest.java
test-commons/src/test/resources/code.js.issues.txt
test-commons/src/test/resources/simple.js

Provide 'git diff' like issue report in the comparison exception message

Provide 'git diff' like issue report in the comparison exception message

---

commons/src/main/java/org/sonarsource/analyzer/commons/ProgressReport.java
commons/src/test/java/org/sonarsource/analyzer/commons/ProgressReportTest.java

Move ProgressReport from sslr-squid-bridge (changed logger and added tests)

---

pom.xml
recognizers/pom.xml
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/CamelCaseDetector.java
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/CodeRecognizer.java
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/ContainsDetector.java
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/Detector.java
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/EndWithDetector.java
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/KeywordsDetector.java
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/LanguageFootprint.java
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/RegexDetector.java
recognizers/src/main/java/org/sonarsource/analyzer/recognizers/package-info.java
recognizers/src/test/java/org/sonarsource/analyzer/recognizers/CamelCaseDetectorTest.java
recognizers/src/test/java/org/sonarsource/analyzer/recognizers/CodeRecognizerTest.java
recognizers/src/test/java/org/sonarsource/analyzer/recognizers/ContainsDetectorTest.java
recognizers/src/test/java/org/sonarsource/analyzer/recognizers/EndWithDetectorTest.java
recognizers/src/test/java/org/sonarsource/analyzer/recognizers/KeywordsDetectorTest.java
recognizers/src/test/java/org/sonarsource/analyzer/recognizers/RegexDetectorTest.java

Add recognizers from sslr-squid-bridge

---

README.md
commons/README.md
commons/src/main/java/org/sonarsource/analyzer/commons/InputFileContentExtractor.java
commons/src/main/java/org/sonarsource/analyzer/commons/ProgressReport.java
commons/src/test/java/org/sonarsource/analyzer/commons/ProgressReportTest.java
recognizers/README.md

Docs + Depr

---

commons/README.md
commons/pom.xml
commons/src/main/java/org/sonarsource/analyzer/commons/FileProvider.java
commons/src/main/java/org/sonarsource/analyzer/commons/PatternDirectoryScanner.java
commons/src/test/java/org/sonarsource/analyzer/commons/FileProviderTest.java
commons/src/test/java/org/sonarsource/analyzer/commons/PatternDirectoryScannerTest.java

Such file provided is useful user-provided reports (e.g. coverage)

Add file provider based on path pattern

---

commons/src/main/java/org/sonarsource/analyzer/commons/ProgressReport.java
commons/src/test/java/org/sonarsource/analyzer/commons/ProgressReportTest.java

Fix Deadlock on ProgressReport (Fixes #151)

---

xml-parsing/src/main/java/org/sonarsource/analyzer/commons/xml/XmlParser.java
xml-parsing/src/test/java/org/sonarsource/analyzer/commons/xml/XmlParserTest.java

SONARXML-149 Fix NPE parsing XML empty CDATA

---

regex-parsing/src/main/java/org/sonarsource/analyzer/commons/regex/finders/SuperfluousCurlyBraceFinder.java
regex-parsing/src/test/java/org/sonarsource/analyzer/commons/regex/finders/SuperfluousCurlyBraceFinderTest.java
regex-parsing/src/test/resources/finders/SuperfluousCurlyBraceFinder.yml

Implement SuperfluousCurlyBraceFinder for rule S6396

---

regex-parsing/src/main/java/org/sonarsource/analyzer/commons/regex/finders/UnquantifiedNonCapturingGroupFinder.java
regex-parsing/src/test/java/org/sonarsource/analyzer/commons/regex/finders/UnquantifiedNonCapturingGroupFinderTest.java
regex-parsing/src/test/resources/finders/UnquantifiedNonCapturingGroupFinder.yml

Related to [SONARPHP-1279](https://jira.sonarsource.com/browse/SONARPHP-1279)

Resolve #198 Implement UnquantifiedNonCapturingGroupFinder for Rule S6395

---

regex-parsing/src/main/java/org/sonarsource/analyzer/commons/regex/finders/EmptyAlternativeFinder.java
regex-parsing/src/test/resources/finders/EmptyAlternativeFinder.yml

There was a misinterpretation of the description of SONARPHP-1274.
This resulted in https://github.com/SonarSource/rspec/pull/779/files and this PR

Modify the behaviour of S6323

---

.github/workflows/release.yml
pom.xml

Release action updated thanks to the [gh-action_release](https://github.com/SonarSource/gh-action_release/blob/master/README.md) indications.

Update parent pom to 61.0.147 and release workflow to v4

---

regex-parsing/src/main/java/org/sonarsource/analyzer/commons/regex/helpers/RegexReachabilityChecker.java
regex-parsing/src/test/resources/finders/ImpossibleBoundaryFinder.yml

Related to [SONARPHP-1238](https://sonarsource.atlassian.net/browse/SONARPHP-1238) and [SONARJAVA-3890](https://sonarsource.atlassian.net/browse/SONARJAVA-3890)

S5996 FP on line breaks after end boundaries

---

commons/src/main/java/org/sonarsource/analyzer/commons/collections/AVLTree.java
commons/src/main/java/org/sonarsource/analyzer/commons/collections/MapEntriesIterable.java
commons/src/main/java/org/sonarsource/analyzer/commons/collections/PMap.java
commons/src/main/java/org/sonarsource/analyzer/commons/collections/TreeIterator.java
commons/src/test/java/org/sonarsource/analyzer/commons/collections/MapEntriesIterableTest.java

Allow iteration over PMap entries (#250)

---

commons/src/main/java/org/sonarsource/analyzer/commons/RuleMetadataLoader.java
commons/src/test/java/org/sonarsource/analyzer/commons/RuleMetadataLoaderTest.java

Read scope from rule json metadata file.

---

commons/src/test/java/org/sonarsource/analyzer/commons/RuleMetadataLoaderTest.java
pom.xml

Issue 3122 rule metadata scope

---

commons/pom.xml
commons/src/main/java/org/sonarsource/analyzer/commons/FileProvider.java
commons/src/test/java/org/sonarsource/analyzer/commons/FileProviderTest.java
pom.xml
recognizers/pom.xml
recognizers/src/main/java/org/sonarsource/analyzer/commons/recognizers/StringUtils.java
recognizers/src/test/java/org/sonarsource/analyzer/commons/recognizers/StringUtilsTest.java

Remove dependency on commons-lang and commons-io, so they don't propagate transitively into other projects.
Please keep the commits separate (rebase)

Remove dependency on commons-lang and commons-io

---

commons/pom.xml
performance-measure/pom.xml
pom.xml
recognizers/pom.xml
regex-parsing/pom.xml
test-commons/pom.xml
test-xml-parsing/pom.xml
xml-parsing/pom.xml

Bumping major version to signal change to Java 11

Bump major version

---

.cirrus.yml
.github/workflows/release.yml

BUILD-2222 Use Vault

---

commons/src/main/java/org/sonarsource/analyzer/commons/EducationRuleLoader.java
commons/src/test/java/org/sonarsource/analyzer/commons/EducationRuleLoaderTest.java
commons/src/test/resources/org/sonarsource/analyzer/commons/S102.html
commons/src/test/resources/org/sonarsource/analyzer/commons/S102_fallback.html
commons/src/test/resources/org/sonarsource/analyzer/commons/education/invalid/S102.html
commons/src/test/resources/org/sonarsource/analyzer/commons/education/valid/S100.html
commons/src/test/resources/org/sonarsource/analyzer/commons/education/valid/S101.html
commons/src/test/resources/org/sonarsource/analyzer/commons/education/valid/S101_fallback.html
commons/src/test/resources/org/sonarsource/analyzer/commons/education/valid/S102.html
commons/src/test/resources/org/sonarsource/analyzer/commons/education/valid/S103.html
commons/src/test/resources/org/sonarsource/analyzer/commons/education/valid/S105.html

Update rule description loading for newest version of education format

---

commons/pom.xml
commons/src/main/java/org/sonarsource/analyzer/commons/EducationRuleLoader.java
commons/src/main/java/org/sonarsource/analyzer/commons/ExternalReportProvider.java
commons/src/main/java/org/sonarsource/analyzer/commons/ProgressReport.java
commons/src/test/java/org/sonarsource/analyzer/commons/EducationRuleLoaderTest.java
commons/src/test/java/org/sonarsource/analyzer/commons/ExternalReportProviderTest.java
commons/src/test/java/org/sonarsource/analyzer/commons/ProgressReportTest.java
performance-measure/pom.xml
performance-measure/src/main/java/org/sonarsource/performance/measure/log/Logger.java
performance-measure/src/main/java/org/sonarsource/performance/measure/log/SonarSourceLoggerBridge.java
performance-measure/src/test/java/org/sonarsource/performance/measure/log/SonarSourceLoggerBridgeTest.java
performance-measure/src/test/java/org/sonarsource/performance/measure/log/StringLogger.java
pom.xml
regex-parsing/pom.xml
regex-parsing/src/main/java/org/sonarsource/analyzer/commons/regex/RegexParser.java
test-xml-parsing/pom.xml
xml-parsing/pom.xml
xml-parsing/src/main/java/org/sonarsource/analyzer/commons/xml/checks/SimpleXPathBasedCheck.java
xml-parsing/src/test/java/org/sonarsource/analyzer/commons/xml/checks/SimpleXPathBasedCheckTest.java

Update sonar-plugin-api to 10.0 and use slf4j Logger

---

.cirrus.yml

Inspired by https://github.com/SonarSource/sonar-dataflow-bug-detection/pull/954, hopefully the same changes here have the same effect

Remove references to burgr

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml

[ACOMMONS-20](https://sonarsource.atlassian.net/browse/ACOMMONS-20)
[ACOMMONS-20]: https://sonarsource.atlassian.net/browse/ACOMMONS-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACOMMONS-20 Add Jira integration

---

.github/workflows/PullRequestClosed.yml

[ACOMMONS-23](https://sonarsource.atlassian.net/browse/ACOMMONS-23)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[ACOMMONS-23]: https://sonarsource.atlassian.net/browse/ACOMMONS-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACOMMONS-23 Autoclose issues created by Jira integration

---

commons/src/main/java/org/sonarsource/analyzer/commons/domain/package-info.java

[ACOMMONS-26](https://sonarsource.atlassian.net/browse/ACOMMONS-26)
[ACOMMONS-26]: https://sonarsource.atlassian.net/browse/ACOMMONS-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACOMMONS-26 Add missing package-info.java for quality gate
